dataset: ml-1m
train_dir: default
batch_size: 128
lr: 0.001
maxlen: 10
hidden_units: 50
num_blocks: 2
num_epochs: 201
log_every_n_steps: 10
check_val_every_n_epoch: 5
num_heads: 1
dropout_rate: 0.5
l2_emb: 0.0
num_workers: 4

hydra:
  run:
    dir: .
  output_subdir: null
  job_logging:
    version: 1
    disable_existing_loggers: true
    root:
      level: ERROR
      handlers: []
    loggers: {}
